### ISSUE TITLE
7.3.0 breaks display on Safari

### ISSUE THREAD

**Issue by njzjz** [theme-next/hexo-theme-next#1046]
It works well if reverted to b01d8258ccadf2541790a55b87ab69c8945eb908

![90175F63-C82D-4B2F-96FF-9FE6BB29389E](https://user-images.githubusercontent.com/9496702/62364946-62720d00-b555-11e9-8c55-c485c0e1cc5d.png)

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by 1v9** [comment]
Please provide your iPhone model, iOS version and your website.

**Comment by njzjz** [comment]
a broken website: https://jinzhe-blog-mrepencft.now.sh/
a normal one: https://jinzhe-blog-4ktlyxzlk.now.sh/

iPhone X
iOS 13.0 Beta 5

Thank you.
————————
Jinzhe Zeng
PhD student in Chemistry
Rutgers University

jinzhe.zeng@rutgers.edu
CV: https://njzjz.win/cv

**Comment by 1v9** [comment]
@njzjz Thanks, in fact I always using latest master branch, but on my site everything is OK. Recently we have updated NexT very frequently, so you may carefully update your theme and configuration and make sure that the personalized settings are still available.

**Comment by stevenjoezhang** [comment]
@njzjz In the latest version, the usage of `custom_logo` has changed.

```diff
-custom_logo:
-  enable: false
-  image: #/uploads/custom-logo.jpg
+custom_logo: #/uploads/custom-logo.jpg
```

**Comment by njzjz** [comment]
> @njzjz In the latest version, the usage of `custom_logo` has changed.
> 
> ```diff
> -custom_logo:
> -  enable: false
> -  image: #/uploads/custom-logo.jpg
> +custom_logo: #/uploads/custom-logo.jpg
> ```

Fix it, but it cannot display yet.
Broken one: https://5d44f285713f1c0007a945ac--distracted-blackwell-060443.netlify.com/
Normal one: https://deploy-preview-221--distracted-blackwell-060443.netlify.com/

btw, I found it cannot display on the Chrome as well.

**Comment by stevenjoezhang** [comment]
This js file is empty: https://5d44f285713f1c0007a945ac--distracted-blackwell-060443.netlify.com/js/utils.js?v=7.3.0

**Comment by njzjz** [comment]
> @njzjz This js file is empty: https://5d44f285713f1c0007a945ac--distracted-blackwell-060443.netlify.com/js/utils.js?v=7.3.0

@stevenjoezhang I checked the log and found these errors:
```
ERROR Asset render failed: js/algolia-search.js
Error
    at new JS_Parse_Error (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1534:18)
    at js_error (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1542:11)
    at parse_error (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1667:9)
    at Object.next_token [as input] (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1946:9)
    at next (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2075:25)
    at eval (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2205:42)
    at eval (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2136:24)
    at block_ (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2429:20)
    at eval (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2401:25)
    at function_ (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2407:15)
    at expr_atom (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2622:24)
    at maybe_unary (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2792:19)
    at expr_ops (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2827:24)
    at maybe_conditional (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2832:20)
    at maybe_assign (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2856:20)
    at expression (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2875:20)
ERROR Asset render failed: js/next-boot.js
Error
    at new JS_Parse_Error (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1534:18)
    at js_error (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1542:11)
    at parse_error (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1667:9)
    at Object.next_token [as input] (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1946:9)
    at next (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2075:25)
    at expect_token (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2108:20)
    at expect (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2113:36)
    at expr_list (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2636:44)
    at subscripts (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2775:30)
    at subscripts (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2752:20)
    at subscripts (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2772:20)
    at expr_atom (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2628:20)
    at maybe_unary (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2792:19)
    at expr_ops (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2827:24)
    at maybe_conditional (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2832:20)
    at maybe_assign (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2856:20)
ERROR Asset render failed: js/scrollspy.js
Error
    at new JS_Parse_Error (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1534:18)
    at js_error (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1542:11)
    at parse_error (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1667:9)
    at Object.next_token [as input] (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1946:9)
    at next (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2075:25)
    at vardefs (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2509:48)
    at var_ (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2522:27)
    at eval (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2265:30)
    at eval (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2136:24)
    at block_ (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2429:20)
    at eval (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2401:25)
    at function_ (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2407:15)
    at expr_atom (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2622:24)
    at maybe_unary (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2792:19)
    at expr_ops (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2827:24)
    at maybe_conditional (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2832:20)
INFO  neat the css: /github/workspace/themes/next/source/css/main.styl [ 17.71% saved]
INFO  Generated: atom.xml
INFO  Generated: sitemap.xml
ERROR Asset render failed: js/local-search.js
Error
    at new JS_Parse_Error (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1534:18)
    at js_error (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1542:11)
    at parse_error (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1667:9)
    at Object.next_token [as input] (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1946:9)
    at next (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2075:25)
    at maybe_assign (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2859:17)
    at expression (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2875:20)
    at simple_statement (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2314:55)
    at eval (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2183:19)
    at eval (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2136:24)
    at block_ (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2429:20)
    at eval (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2401:25)
    at function_ (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2407:15)
    at expr_atom (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2622:24)
    at maybe_unary (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2792:19)
    at expr_ops (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2827:24)
ERROR Asset render failed: js/utils.js
Error
    at new JS_Parse_Error (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1534:18)
    at js_error (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1542:11)
    at parse_error (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1667:9)
    at Object.next_token [as input] (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1946:9)
    at next (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2075:25)
    at subscripts (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2771:13)
    at subscripts (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2752:20)
    at expr_atom (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2628:20)
    at maybe_unary (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2792:19)
    at expr_ops (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2827:24)
    at maybe_conditional (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2832:20)
    at maybe_assign (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2856:20)
    at maybe_assign (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2864:32)
    at expression (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2875:20)
    at simple_statement (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2314:55)
    at eval (eval at <anonymous> (/github/workspace/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2183:19)
INFO  neat the js: /github/workspace/themes/next/source/lib/velocity/velocity.ui.min.js [ 1.21% saved]
INFO  Generated: index.html
INFO  Generated: 404.html
INFO  Generated: CNAME
···

**Comment by stevenjoezhang** [comment]
This is not theme NexT's error message. Are you using any plugins to compress / minify js files?

**Comment by njzjz** [comment]
I use [hexo-neat](https://github.com/rozbo/hexo-neat). I will try to close it.

**Comment by njzjz** [comment]
After I disable compressing, [utils.js](https://jinzhe-blog-e409ugwgd.now.sh/js/utils.js?v=7.3.0) works well. I download it and tried to compress with `uglifyjs` and get the error:
```
(base) jzzeng@ZENG-SURFACE:~/test$ uglifyjs utils.js                                                                                                  Parse error at utils.js:17,39
          $imageWrapLink = $image.wrap(`<a class="fancybox fancybox.image" href=
                                       ^
ERROR: Unexpected character '`'
    at JS_Parse_Error.get (eval at <anonymous> (/home/jzzeng/anaconda3/lib/node_modules/uglify-js/tools/node.js:20:1), <anonymous>:71:23)
    at fatal (/home/jzzeng/anaconda3/lib/node_modules/uglify-js/bin/uglifyjs:298:27)
    at run (/home/jzzeng/anaconda3/lib/node_modules/uglify-js/bin/uglifyjs:241:9)
    at Object.<anonymous> (/home/jzzeng/anaconda3/lib/node_modules/uglify-js/bin/uglifyjs:167:5)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
```
The reason is that `uglifyjs` doesn't support ES6. I will try another plugin.
Thank you.

**Comment by stevenjoezhang** [comment]
You can try to use `uglifyes`. It's similar to `uglifyjs`, but come up with ES6 syntax support.
