### ISSUE TITLE
bug of latest version next theme 

### ISSUE THREAD

**Issue by BrooksJoshua** [theme-next/hexo-theme-next#1153]
I installed next 7.4.0, but when i execute the : hexo clean command, it presented a bug shown as below:
ERROR Deployer not found: git

then I executed: npm install hexo-deployer-git --save
still, did not work out and reported a bug as:

ERROR Plugin load failed: hexo-deployer-git

followed by:
/Users/willleeon/Library/myhexo/node_modules/hexo-deployer-git/node_modules/chokidar/index.js:121
  async remove(item) {
        ^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/willleeon/Library/myhexo/node_modules/hexo-deployer-git/node_modules/hexo-fs/lib/fs.js:6:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/willleeon/Library/myhexo/node_modules/hexo-deployer-git/lib/deployer.js:4:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

anyone can help?  Thanks a loooot!

**Comment by stevenjoezhang** [comment]
Upgrade node.js to the latest version.
If the issue still exist, please ask Hexo team for help: https://github.com/hexojs/hexo-deployer-git/issues
