### ISSUE TITLE
" hexo new page " error

### ISSUE THREAD

**Issue by 1am-one** [theme-next/hexo-theme-next#1208]
## Issue Checklist 

- [x] I have executed `hexo clean`, cleared the browser cache and disabled all CDN services (e.g. Cloudflare Rocket Loader), this issue still exists.
- [ ] I have confirmed that this issue only appears in theme NexT, but cannot be reproduced in other themes (e.g. default theme landscape). In other words, prove that this is a NexT issue, not a issue from Hexo.
- [x] I have already viewed [NexT Documentation Site](http://theme-next.org/docs/) and [Hexo Docs page](https://hexo.io/docs/), especially [Troubleshooting](https://hexo.io/docs/troubleshooting.html) part.
- [x] I have already viewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Expected behavior 

When I type hexo new page "_else" 
I want it to build a forder named "_else" in the forder "sourses"

## Actual behavior 

It didn't do it and report error, which I find in troubleshooting says that "Make sure you are using soft tabs and add a space after colons." . But I did check them and the problem still.  

this is the error report: 
(the /aiguosb is my blog's root forder)

$ hexo new page "_else"
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 5, column 1:

    ^
    at generateError (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\js-yaml\lib\js-yaml\loader.js:167:10)
    at throwError (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\js-yaml\lib\js-yaml\loader.js:173:9)
    at readBlockMapping (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\js-yaml\lib\js-yaml\loader.js:1073:9)
    at composeNode (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\js-yaml\lib\js-yaml\loader.js:1359:12)
    at readDocument (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\js-yaml\lib\js-yaml\loader.js:1519:3)
    at loadDocuments (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\js-yaml\lib\js-yaml\loader.js:1575:5)
    at Object.load (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\js-yaml\lib\js-yaml\loader.js:1596:19)
    at _getScaffold.then.then.frontMatter (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\hexo\lib\hexo\post.js:125:66)
    at tryCatcher (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\bluebird\js\release\promise.js:699:18)
    at Promise._fulfill (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\bluebird\js\release\promise.js:643:18)
    at Promise._resolveCallback (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\bluebird\js\release\promise.js:437:57)
    at Promise._settlePromiseFromHandler (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\bluebird\js\release\promise.js:529:17)
    at Promise._settlePromise (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\bluebird\js\release\promise.js:699:18)
    at Promise._fulfill (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\bluebird\js\release\promise.js:643:18)
    at Promise._settlePromise (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\bluebird\js\release\promise.js:587:21)
    at Promise._settlePromise0 (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\bluebird\js\release\promise.js:619:10)

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. I open git bash on my blog's root forder. 
2. I type hexo new page "_else" and enter. 
3. The git bash just report error. 

### Node.js and NPM Information

```

$ node -v
v10.16.3

$ npm -v
6.9.0

```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.9.0"
  },
  "dependencies": {
    "hexo": "^3.9.0",
    "hexo-blog-encrypt": "^3.0.3",
    "hexo-deployer-git": "^2.0.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index-pin-top": "^0.2.2",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^1.0.1",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3"
  }
}

```

### Hexo Version

```
$ hexo -v
hexo: 3.9.0
hexo-cli: 3.0.0
os: Windows_NT 6.1.7601 win32 x64
http_parser: 2.8.0
node: 10.16.3
v8: 6.8.275.32-node.54
uv: 1.28.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 64
nghttp2: 1.39.2
napi: 4
openssl: 1.1.1c
icu: 64.2
unicode: 12.1
cldr: 35.1
tz: 2019a

```

### Hexo Configuration

```yml
I have check all the space after colon:
```

### NexT Configuration

```yml
I have check all the part that I've changed 
there do are space after colon:
```

**Comment by stevenjoezhang** [comment]
Switch to default theme landscape and try again.

**Comment by stevenjoezhang** [comment]
Maybe you can open an issue here: https://github.com/hexojs/hexo/issues

![屏幕快照 2019-10-10 下午6 23 54](https://user-images.githubusercontent.com/16272760/66561108-6476ce80-eb8b-11e9-8be0-d9d5f247a995.png)
I thought the Issue checklist was clear enough. 😢

**Comment by 1am-one** [comment]
> 
> 
> Maybe you can open an issue here: https://github.com/hexojs/hexo/issues
> 
> ![屏幕快照 2019-10-10 下午6 23 54](https://user-images.githubusercontent.com/16272760/66561108-6476ce80-eb8b-11e9-8be0-d9d5f247a995.png)
> I thought the Issue checklist was clear enough. cry
> 
> > <img alt="" width="48" src="https://avatars0.githubusercontent.com/u/6375567?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/4908d9947135e4536ef61d61512ee575f869bf6f/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e2e69636f"> GitHub**[hexojs/hexo](https://github.com/hexojs/hexo)**A fast, simple & powerful blog framework, powered by Node.js. - hexojs/hexo

all right. thank you anyway.
