### ISSUE TITLE
Cannot enable disqusJS

### ISSUE THREAD

**Issue by EdisonJwa** [theme-next/hexo-theme-next#1239]
Please check if your Issue fulfills the following requirements.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。

## Issue Checklist 

- [x] I have executed `hexo clean`, cleared the browser cache and disabled all CDN services (e.g. Cloudflare Rocket Loader), this issue still exists.
- [x] I have confirmed that this issue only appears in theme NexT, but cannot be reproduced in other themes (e.g. default theme landscape). In other words, prove that this is a NexT issue, not a issue from Hexo.
- [x] I have already viewed [NexT Documentation Site](http://theme-next.org/docs/) and [Hexo Docs page](https://hexo.io/docs/), especially [Troubleshooting](https://hexo.io/docs/troubleshooting.html) part.
- [x] I have already viewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Expected behavior 
enable disqusJS comment system

## Actual behavior 

When I was trying to enable disqusJS comment system on my blog, I got the following errors

```bash
ERROR Render HTML failed: archives/test/index.html
TypeError: Cannot read property 'indexOf' of null
    at Hexo.<anonymous> (/edison/blog/node_modules/hexo-spoiler/index.js:42:12)
    at Hexo.tryCatcher (/edison/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/edison/blog/node_modules/bluebird/js/release/method.js:15:34)
    at /edison/blog/node_modules/hexo/lib/extend/filter.js:60:50
    at tryCatcher (/edison/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/edison/blog/node_modules/bluebird/js/release/reduce.js:166:18)
    at Object.gotAccum (/edison/blog/node_modules/bluebird/js/release/reduce.js:155:25)
    at Object.tryCatcher (/edison/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/edison/blog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/edison/blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/edison/blog/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/edison/blog/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/edison/blog/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/edison/blog/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/edison/blog/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
Unhandled rejection TypeError: Cannot read property 'indexOf' of null
    at Hexo.<anonymous> (/edison/blog/node_modules/hexo-spoiler/index.js:42:12)
    at Hexo.tryCatcher (/edison/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/edison/blog/node_modules/bluebird/js/release/method.js:15:34)
    at /edison/blog/node_modules/hexo/lib/extend/filter.js:60:50
    at tryCatcher (/edison/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/edison/blog/node_modules/bluebird/js/release/reduce.js:166:18)
    at Object.gotAccum (/edison/blog/node_modules/bluebird/js/release/reduce.js:155:25)
    at Object.tryCatcher (/edison/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/edison/blog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/edison/blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/edison/blog/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/edison/blog/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/edison/blog/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/edison/blog/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/edison/blog/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
```

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: 
config file of this part
```yml
disqusjs:
  enable: true
  api: 
  apikey: vBTqc5gYirQfuj9STIAANtQCArVi9MN8UZ72UUucwnhus4AhpgpbVJMIn3Ojl4O7
  shortname: edisonj
```

## Steps to reproduce the behavior 
1. Enable DisqusJS on local

### Node.js and NPM Information

```bash
v12.11.1
6.12.0
```

### Package dependencies Information

```json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "4.0.0"
  },
  "dependencies": {
    "hexo": "^4.0.0",
    "hexo-cdnify": "^0.0.2",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-baidu-sitemap": "^0.1.6",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^2.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-searchdb": "^1.1.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0",
    "hexo-spoiler": "^1.5.2",
    "hexo-symbols-count-time": "^0.6.3",
    "hexo-tag-aplayer": "^3.0.4",
    "hexo-uglify": "^1.0.0"
  }
}
```

### Hexo Version

```bash
hexo: 4.0.0
hexo-cli: 3.1.0
os: Darwin 18.7.0 darwin x64
node: 12.11.1
v8: 7.7.299.11-node.12
uv: 1.32.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 72
nghttp2: 1.39.2
napi: 5
llhttp: 1.1.4
http_parser: 2.8.0
openssl: 1.1.1c
cldr: 35.1
icu: 64.2
tz: 2019a
unicode: 12.1
```

### Hexo Configuration

**not the business of this part**

### NexT Configuration

```yml
disqusjs:
  enable: true
  api: 
  apikey: vBTqc5gYirQfuj9STIAANtQCArVi9MN8UZ72UUucwnhus4AhpgpbVJMIn3Ojl4O7
  shortname: edisonj
```

**Comment by stevenjoezhang** [comment]
卸载`hexo-spoiler`插件后情况如何？

**Comment by EdisonJwa** [comment]
> 卸载`hexo-spoiler`插件后情况如何？

https://paste.ubuntu.com/p/vxRvvFtvJ3/

**Comment by stevenjoezhang** [comment]
已修复： https://github.com/theme-next/hexo-theme-next/commit/89014c3150f68845b6d72592fa4078006c2c6116
