### ISSUE TITLE
最新版的Next使用site.posts获取文章出错

### ISSUE THREAD

**Issue by Such360996299** [theme-next/hexo-theme-next#1265]
我想实现一个近期文章的功能，但在使用site.posts获取文章的title和path时出错。

hexo\themes\next\layout\_macro\sidebar.swig:
```bash
<ul class="links-of-blogroll-list">
                  {% set posts = site.posts.sort('-date') %}
                  {% for post in posts.slice('0', '5') %}
                    <li class='my-links-of-blogroll-li'>
                      <a href="{{ url_for(post.path) }}" title= "{{ post.title }}" target="_blank">{{ post.title }}</a>
                    </li>
                  {% endfor %}
                </ul>
```
Code after web page deployment：
![123](https://user-images.githubusercontent.com/37107669/68439441-928b1500-0202-11ea-996a-040ae60cda53.png)

版本：
Hexo：4.0.0
Next：7.5.0

当我切换使用Next版本为：5.1.4时，上述代码正常，成功获取。

**Comment by 1v9** [comment]
尝试 `toArray()`，NexT 已经更换 Nunjucks 作为模板引擎。

**Comment by Such360996299** [comment]
> 尝试 `toArray()`，NexT 已经更换 Nunjucks 作为模板引擎。

非常感谢你的回复！！toArray成功了，可是无法sort，能再指导下我怎么按时间排序吗？不熟悉Nunjucks。

**Comment by stevenjoezhang** [comment]
这些都是Hexo的设计，与NexT主题本身无关。或许您可以向Hexo寻求帮助？

**Comment by Such360996299** [comment]
> 这些都是Hexo的设计，与NexT主题本身无关。或许您可以向Hexo寻求帮助？

确实是与主题模板有关，toArray后就成功显示了，目前还不知如何按时间sort。

**Comment by stevenjoezhang** [comment]
`site.posts`获取到的是一个Hexo封装过的对象，您可以找一些Hexo官方的插件看一下相关的源码。`sort('-date')`应该是正确的。

**Comment by Such360996299** [comment]
> `site.posts`获取到的是一个Hexo封装过的对象，您可以找一些Hexo官方的插件看一下相关的源码。`sort('-date')`应该是正确的。

ERROR Render HTML failed: 404.html
TypeError: Cannot read property 'replace' of null
    at Hexo.externalLinkFilter (E:\hexo\node_modules\hexo\lib\plugins\filter\after_render\external_link.js:45:15)
    at Hexo.tryCatcher (E:\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (E:\hexo\node_modules\bluebird\js\release\method.js:15:34)
    at Promise.each.filter (E:\hexo\node_modules\hexo\lib\extend\filter.js:60:50)
    at tryCatcher (E:\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (E:\hexo\node_modules\bluebird\js\release\reduce.js:166:18)
    at Object.gotAccum (E:\hexo\node_modules\bluebird\js\release\reduce.js:155:25)
    at Object.tryCatcher (E:\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\hexo\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\hexo\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (E:\hexo\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (E:\hexo\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (E:\hexo\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\hexo\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\hexo\node_modules\bluebird\js\release\async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
ERROR Render HTML failed: categories/index.html
TypeError: Cannot read property 'replace' of null
    at Hexo.externalLinkFilter (E:\hexo\node_modules\hexo\lib\plugins\filter\after_render\external_link.js:45:15)

不行，这样也会报错。
