### ISSUE TITLE
新版本主题如何对site.posts.toArray()生成的数组进行排序？

### ISSUE THREAD

**Issue by Such360996299** [theme-next/hexo-theme-next#1266]
尝试了
```bash
site.posts.toArray().sort('-date')
```
或
```bash
site.posts.toArray().sort(function(a,b){
　　return a.date - b.date
})
```
等多种方法，都出现如下报错（报错代码片段）：
ERROR Render HTML failed: 404.html
TypeError: Cannot read property 'replace' of null
    at Hexo.externalLinkFilter (E:\hexo\node_modules\hexo\lib\plugins\filter\after_render\external_link.js:45:15)
    at Hexo.tryCatcher (E:\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (E:\hexo\node_modules\bluebird\js\release\method.js:15:34)
    at Promise.each.filter (E:\hexo\node_modules\hexo\lib\extend\filter.js:60:50)
    at tryCatcher (E:\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (E:\hexo\node_modules\bluebird\js\release\reduce.js:166:18)
    at Object.gotAccum (E:\hexo\node_modules\bluebird\js\release\reduce.js:155:25)
    at Object.tryCatcher (E:\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\hexo\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\hexo\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (E:\hexo\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (E:\hexo\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (E:\hexo\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\hexo\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\hexo\node_modules\bluebird\js\release\async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
ERROR Render HTML failed: categories/index.html
TypeError: Cannot read property 'replace' of null
    at Hexo.externalLinkFilter (E:\hexo\node_modules\hexo\lib\plugins\filter\after_render\external_link.js:45:15)
    at Hexo.tryCatcher (E:\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (E:\hexo\node_modules\bluebird\js\release\method.js:15:34)
    at Promise.each.filter (E:\hexo\node_modules\hexo\lib\extend\filter.js:60:50)
    at tryCatcher (E:\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (E:\hexo\node_modules\bluebird\js\release\reduce.js:166:18)
    at Object.gotAccum (E:\hexo\node_modules\bluebird\js\release\reduce.js:155:25)

**Comment by stevenjoezhang** [comment]
https://github.com/theme-next/hexo-theme-next/issues/1265#issuecomment-551762608

NexT不对此负责，我们也不建议在NexT的Issue中讨论此问题。请向Hexo寻求帮助，祝您使用愉快！

**Comment by stevenjoezhang** [comment]
您所使用的全局变量全部来自于Hexo。NexT主题本身对此无能为力。
