### ISSUE TITLE
使用clone的主题后，博客page/4/index.html 渲染失败

### ISSUE THREAD

**Issue by OltremareXd** [theme-next/hexo-theme-next#1319]
在直接clone next模板，在站点配置文件修改主题为next后直接`hexo g && hexo s`。
结果提示
```
ERROR Render HTML failed: page/4/index.html
TypeError: Cannot read property 'parent' of null
    at Function.exports.update (C:\Users\12404\Desktop\hexo\node_modules\cheerio\lib\parse.js:55:26)
    at module.exports (C:\Users\12404\Desktop\hexo\node_modules\cheerio\lib\parse.js:17:11)
    at Function.exports.load (C:\Users\12404\Desktop\hexo\node_modules\cheerio\lib\static.js:22:14)
    at Hexo.hexoMetaGeneratorInject (C:\Users\12404\Desktop\hexo\node_modules\hexo\lib\plugins\filter\meta_generator.js:8:21)
    at Hexo.tryCatcher (C:\Users\12404\Desktop\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (C:\Users\12404\Desktop\hexo\node_modules\bluebird\js\release\method.js:15:34)
    at Promise.each.filter (C:\Users\12404\Desktop\hexo\node_modules\hexo\lib\extend\filter.js:60:50)
    at tryCatcher (C:\Users\12404\Desktop\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (C:\Users\12404\Desktop\hexo\node_modules\bluebird\js\release\reduce.js:155:18)
    at Object.gotAccum (C:\Users\12404\Desktop\hexo\node_modules\bluebird\js\release\reduce.js:144:25)
    at Object.tryCatcher (C:\Users\12404\Desktop\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\12404\Desktop\hexo\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (C:\Users\12404\Desktop\hexo\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromiseCtx (C:\Users\12404\Desktop\hexo\node_modules\bluebird\js\release\promise.js:611:10)           at _drainQueueStep (C:\Users\12404\Desktop\hexo\node_modules\bluebird\js\release\async.js:142:12)
    at _drainQueue (C:\Users\12404\Desktop\hexo\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (C:\Users\12404\Desktop\hexo\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\12404\Desktop\hexo\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
ERROR Cannot read property 'parent' of null
TypeError: Cannot read property 'parent' of null
    at Function.exports.update (C:\Users\12404\Desktop\hexo\node_modules\cheerio\lib\parse.js:55:26)
    at module.exports (C:\Users\12404\Desktop\hexo\node_modules\cheerio\lib\parse.js:17:11)
    at Function.exports.load (C:\Users\12404\Desktop\hexo\node_modules\cheerio\lib\static.js:22:14)
    at Hexo.hexoMetaGeneratorInject (C:\Users\12404\Desktop\hexo\node_modules\hexo\lib\plugins\filter\meta_generator.js:8:21)
    at Hexo.tryCatcher (C:\Users\12404\Desktop\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (C:\Users\12404\Desktop\hexo\node_modules\bluebird\js\release\method.js:15:34)
    at Promise.each.filter (C:\Users\12404\Desktop\hexo\node_modules\hexo\lib\extend\filter.js:60:50)
    at tryCatcher (C:\Users\12404\Desktop\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (C:\Users\12404\Desktop\hexo\node_modules\bluebird\js\release\reduce.js:155:18)
    at Object.gotAccum (C:\Users\12404\Desktop\hexo\node_modules\bluebird\js\release\reduce.js:144:25)
    at Object.tryCatcher (C:\Users\12404\Desktop\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\12404\Desktop\hexo\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (C:\Users\12404\Desktop\hexo\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromiseCtx (C:\Users\12404\Desktop\hexo\node_modules\bluebird\js\release\promise.js:611:10)           at _drainQueueStep (C:\Users\12404\Desktop\hexo\node_modules\bluebird\js\release\async.js:142:12)
    at _drainQueue (C:\Users\12404\Desktop\hexo\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (C:\Users\12404\Desktop\hexo\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\12404\Desktop\hexo\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

**Comment by OltremareXd** [comment]
切换到v7.5版本后不再报错
