### ISSUE TITLE
ERROR Render HTML failed: study/index.html

### ISSUE THREAD

**Issue by ProfessorX** [theme-next/hexo-theme-next#1370]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x ] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x ] I have reviewed [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md), especially the [Before Submitting An Issue](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md#before-submitting-an-issue) part.
- [x ] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Expected behavior 

`hexo g`正常编译md文件，并生成html文件。

## Actual behavior 

- Links to demo site with this issue: https://www.yxiao.org
- Links to repository or source code of the blog:  https://github.com/ProfessorX/hexo-source

7.5版本正常 7.2.0版本正常
7.7.1报错

## Steps to reproduce the behavior 
1. `git clone https://github.com/ProfessorX/hexo-source ./`
2. git pull theme-next master branch
3. `npm update`
4. `npm audit fix`
5. `hexo g`

```powershell
INFO  Start processing
INFO  Files loaded in 3.55 s
ERROR Render HTML failed: study/index.html
TypeError [ERR_INVALID_URL]: Invalid URL: //
    at onParseError (internal/url.js:243:9)
    at new URL (internal/url.js:319:5)
    at C:\Users\abrah\Documents\blog\node_modules\hexo\node_modules\hexo-util\lib\is_external_link.js:21:18
    at Cache.apply (C:\Users\abrah\Documents\blog\node_modules\hexo\node_modules\hexo-util\lib\cache.js:27:46)
    at isExternalLink (C:\Users\abrah\Documents\blog\node_modules\hexo\node_modules\hexo-util\lib\is_external_link.js:19
    at C:\Users\abrah\Documents\blog\node_modules\hexo\lib\plugins\filter\after_render\external_link.js:23:35
    at String.replace (<anonymous>)
    at Hexo.externalLinkFilter (C:\Users\abrah\Documents\blog\node_modules\hexo\lib\plugins\filter\after_render\external
    at Hexo.tryCatcher (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\method.js:15:34)
    at C:\Users\abrah\Documents\blog\node_modules\hexo\lib\extend\filter.js:62:52
    at tryCatcher (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\reduce.js:155:18)
    at Object.gotAccum (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\reduce.js:144:25)
    at Object.tryCatcher (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\promise.js:517:
    at Promise._settlePromise (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromiseCtx (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\promise.js:611:10)
    at _drainQueueStep (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\async.js:142:12)
    at _drainQueue (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\asy
ERROR Render HTML failed: tweet/index.html
TypeError [ERR_INVALID_URL]: Invalid URL: //
    at onParseError (internal/url.js:243:9)
    at new URL (internal/url.js:319:5)
    at C:\Users\abrah\Documents\blog\node_modules\hexo\node_modules\hexo-util\lib\is_external_link.js:21:18
    at Cache.apply (C:\Users\abrah\Documents\blog\node_modules\hexo\node_modules\hexo-util\lib\cache.js:27:46)
    at isExternalLink (C:\Users\abrah\Documents\blog\node_modules\hexo\node_modules\hexo-util\lib\is_external_link.js:19
    at C:\Users\abrah\Documents\blog\node_modules\hexo\lib\plugins\filter\after_render\external_link.js:23:35
    at String.replace (<anonymous>)
    at Hexo.externalLinkFilter (C:\Users\abrah\Documents\blog\node_modules\hexo\lib\plugins\filter\after_render\external
    at Hexo.tryCatcher (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\method.js:15:34)
    at C:\Users\abrah\Documents\blog\node_modules\hexo\lib\extend\filter.js:62:52
    at tryCatcher (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\reduce.js:155:18)
    at Object.gotAccum (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\reduce.js:144:25)
    at Object.tryCatcher (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\promise.js:517:
    at Promise._settlePromise (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromiseCtx (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\promise.js:611:10)
    at _drainQueueStep (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\async.js:142:12)
    at _drainQueue (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\asy
ERROR Render HTML failed: page/3/index.html
TypeError: Cannot read property 'replace' of null
    at Hexo.externalLinkFilter (C:\Users\abrah\Documents\blog\node_modules\hexo\lib\plugins\filter\after_render\external
    at Hexo.tryCatcher (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\method.js:15:34)
    at C:\Users\abrah\Documents\blog\node_modules\hexo\lib\extend\filter.js:62:52
    at tryCatcher (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\reduce.js:155:18)
    at Object.gotAccum (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\reduce.js:144:25)
    at Object.tryCatcher (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\promise.js:517:
    at Promise._settlePromise (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromiseCtx (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\promise.js:611:10)
    at _drainQueueStep (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\async.js:142:12)
    at _drainQueue (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\asy
    at processImmediate (internal/timers.js:439:21)
ERROR Invalid URL: //
TypeError [ERR_INVALID_URL]: Invalid URL: //
    at onParseError (internal/url.js:243:9)
    at new URL (internal/url.js:319:5)
    at C:\Users\abrah\Documents\blog\node_modules\hexo\node_modules\hexo-util\lib\is_external_link.js:21:18
    at Cache.apply (C:\Users\abrah\Documents\blog\node_modules\hexo\node_modules\hexo-util\lib\cache.js:27:46)
    at isExternalLink (C:\Users\abrah\Documents\blog\node_modules\hexo\node_modules\hexo-util\lib\is_external_link.js:19
    at C:\Users\abrah\Documents\blog\node_modules\hexo\lib\plugins\filter\after_render\external_link.js:23:35
    at String.replace (<anonymous>)
    at Hexo.externalLinkFilter (C:\Users\abrah\Documents\blog\node_modules\hexo\lib\plugins\filter\after_render\external
    at Hexo.tryCatcher (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\method.js:15:34)
    at C:\Users\abrah\Documents\blog\node_modules\hexo\lib\extend\filter.js:62:52
    at tryCatcher (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\reduce.js:155:18)
    at Async._drainQueues (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\async.js:17:14)
ERROR Cannot read property 'replace' of null
TypeError: Cannot read property 'replace' of null
    at Hexo.externalLinkFilter (C:\Users\abrah\Documents\blog\node_modules\hexo\lib\plugins\filter\after_render\external_link.js:22:15)
    at Hexo.<anonymous> (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\method.js:15:34)
    at tryCatcher (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotAccum (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\reduce.js:144:25)
    at Object.tryCatcher (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\promise.js:574:18)            at Promise._settlePromiseCtx (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\promise.js:611:10)         at _drainQueueStep (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\async.js:142:12)
    at _drainQueue (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate (internal/timers.js:439:21)
INFO  0 files generated in 3.54 s
```

### Node.js and NPM Information

```
node v12.10.0
npm 6.10.3
```

### Package dependencies Information

```
+-- hexo@4.2.0
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-category@0.1.3
+-- hexo-generator-index@0.2.1
+-- hexo-generator-search@2.4.0
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@1.0.1
+-- hexo-renderer-stylus@0.3.3
`-- hexo-server@0.3.3
```

### Hexo Configuration

```yml
https://gist.github.com/ProfessorX/34b943d07bad718f2ed41a1bffc1128a
```

### NexT Configuration

```yml
https://gist.github.com/ProfessorX/34b943d07bad718f2ed41a1bffc1128a
```
https://github.com/ProfessorX/theme-next
不记得修改哪里了，可以去我repo看。。。

## Other Information 
System Windows 10 latest version

**Comment by jiangtj** [comment]
检查一下的md文件(${hexo}/source中)，是否存在错误的url，如果存在，新版本的hexo会抛错

Check the md file (${hexo}/source) for the wrong url, and if true, the new version of hexo will be thrown wrong

**Comment by ProfessorX** [comment]
应该是有失效的url.

我去那几个文件里面排查一下。

**Comment by ProfessorX** [comment]
> 检查一下的md文件(${hexo}/source中)，是否存在错误的url，如果存在，新版本的hexo会抛错
> 
> Check the md file (${hexo}/source) for the wrong url, and if true, the new version of hexo will be thrown wrong

试了一下，还是报同样的错误。

我把tweet index.md和study index.md里面所有的链接都删掉了还是不行。

源码在https://github.com/ProfessorX/hexo-source 

已经更新了，你拉下来本地编译一下，帮忙排查看看？多谢！

**Comment by ProfessorX** [comment]
> 检查一下的md文件(${hexo}/source中)，是否存在错误的url，如果存在，新版本的hexo会抛错
> 
> Check the md file (${hexo}/source) for the wrong url, and if true, the new version of hexo will be thrown wrong

-------
找到出错原因了。

新版本hexo 对md文件中
作者：秦怡丁
链接：<https://www.zhihu.com/question/36540597/answer/129987936>
来源：知乎
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。

这种有 `//` 的编译无法支持，会报错。  不过很奇怪，为啥会报无效url.

**Comment by ProfessorX** [comment]
作者：Eagle.F.W
链接：<https://www.zhihu.com/question/23130192/answer/51672159>
来源：知乎
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。


-------
老版本的知乎转载中，链接的引用是带了尖括号的 `<>` 所以parser无法正确识别里面的链接 

LOL

新版本就没这个问题了。

可以关了。

**Comment by ProfessorX** [comment]
study 和 index 修正了。

把抬头的 
permlink /study/ 删掉了能正确编译了。

现在在查找 cannot read property replace of null 这个问题。

**Comment by ProfessorX** [comment]
两个 `invalid url`问题解决了。
-------
这个
```powershell
PS C:\Users\abrah\Documents\blog> hexo s
INFO  Start processing
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
ERROR Render HTML failed: page/3/index.html
TypeError: Cannot read property 'replace' of null
    at Hexo.externalLinkFilter (C:\Users\abrah\Documents\blog\node_modules\hexo\lib\plugins\filter\after_render\external_link.js:22:15)
    at Hexo.tryCatcher (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\method.js:15:34)
    at C:\Users\abrah\Documents\blog\node_modules\hexo\lib\extend\filter.js:62:52
    at tryCatcher (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\reduce.js:155:18)
    at Object.gotAccum (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\reduce.js:144:25)
    at Object.tryCatcher (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\promise.js:517:31)          at Promise._settlePromise (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromiseCtx (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\promise.js:611:10)
    at _drainQueueStep (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\async.js:142:12)
    at _drainQueue (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate (internal/timers.js:439:21)
Unhandled rejection TypeError: Cannot read property 'replace' of null
    at Hexo.externalLinkFilter (C:\Users\abrah\Documents\blog\node_modules\hexo\lib\plugins\filter\after_render\external_link.js:22:15)
    at Hexo.tryCatcher (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\method.js:15:34)
    at C:\Users\abrah\Documents\blog\node_modules\hexo\lib\extend\filter.js:62:52
    at tryCatcher (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\reduce.js:155:18)
    at Object.gotAccum (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\reduce.js:144:25)
    at Object.tryCatcher (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\promise.js:517:31)          at Promise._settlePromise (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromiseCtx (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\promise.js:611:10)
    at _drainQueueStep (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\async.js:142:12)
    at _drainQueue (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\abrah\Documents\blog\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate (internal/timers.js:439:21)
```
问题还是存在。

只是不能生成第三页的index.html  但是我点进去看一下每篇文章都能够生成。

看js的报错提示信息，显示跟外链有关系。

**Comment by ProfessorX** [comment]
hexo config 里面 theme 换成landscape 能够正常编译，没有报错。

在next 下面会报一个外链的错误，最奇怪的是文章都能够正常编译， /page/3/index.html 这个地方会报`cannot read property 'replace' of null`

希望协助解决哈（之前7.5.0的时候没啥问题。）

实在不行我就回退一下theme-next版本。

**Comment by ProfessorX** [comment]
解决。

具体可以参考 2019-11-24-i-was-laid-off post

之前的标题过长，标题里面还有 %号

因为我不怎么会前端，所以只能枚举法。

-------
应该是标题 "***%bala bala " 导致 external_links.js 文件不能够正确的用正则解析搞出来的鬼。

```
---
layout: post
title:  "如果经济危机全面爆发，货币贬值99.9999% 那么我欠银行的100万房贷是还100万，还是100亿？"
date:   2019-11-24  19:00:00 +0800
categories: Report
tags: [World, Economy, Bank, Loan, Depreciation]
---
```
-------
你们可以搞个类似文件去测试一下。

**Comment by ProfessorX** [comment]
> 检查一下的md文件(${hexo}/source中)，是否存在错误的url，如果存在，新版本的hexo会抛错
> 
> Check the md file (${hexo}/source) for the wrong url, and if true, the new version of hexo will be thrown wrong

问题解决了，是一个post 文件名不能够被 libs/.../filter/after_render_external_links.js 正确解析 导致的。
