### ISSUE TITLE
hexo s后访问网站出现TypeError: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by xjywhu** [theme-next/hexo-theme-next#1371]
$ hexo s
INFO  Start processing
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
Unhandled rejection Template render error: (C:\Users\dell\Desktop\Hexo\themes\hexo-                                                                                                                               theme-next-master\layout\post.swig) [Line 3, Column 12]
  Template render error: (C:\Users\dell\Desktop\Hexo\themes\hexo-theme-next-master\                                                                                                                               layout\_partials\head\head.swig) [Line 60, Column 14]
  TypeError: Cannot read property 'path' of undefined
    at Object._prettifyError (C:\Users\dell\Desktop\Hexo\node_modules\nunjucks\src\                                                                                                                               lib.js:36:11)
    at C:\Users\dell\Desktop\Hexo\node_modules\nunjucks\src\environment.js:567:19
    at Template.root [as rootRenderFunc] (eval at _compile (C:\Users\dell\Desktop\H                                                                                                                               exo\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:186:3)
    at eval (eval at _compile (C:\Users\dell\Desktop\Hexo\node_modules\nunjucks\src                                                                                                                               \environment.js:637:18), <anonymous>:35:16)
    at eval (eval at _compile (C:\Users\dell\Desktop\Hexo\node_modules\nunjucks\src                                                                                                                               \environment.js:637:18), <anonymous>:30:46)
    at eval (eval at _compile (C:\Users\dell\Desktop\Hexo\node_modules\nunjucks\src                                                                                                                               \environment.js:637:18), <anonymous>:30:86)
    at eval (eval at _compile (C:\Users\dell\Desktop\Hexo\node_modules\nunjucks\src                                                                                                                               \environment.js:637:18), <anonymous>:26:46)
    at eval (eval at _compile (C:\Users\dell\Desktop\Hexo\node_modules\nunjucks\src                                                                                                                               \environment.js:637:18), <anonymous>:26:86)
    at eval (eval at _compile (C:\Users\dell\Desktop\Hexo\node_modules\nunjucks\src                                                                                                                               \environment.js:637:18), <anonymous>:22:46)
    at eval (eval at _compile (C:\Users\dell\Desktop\Hexo\node_modules\nunjucks\src                                                                                                                               \environment.js:637:18), <anonymous>:22:84)
    at C:\Users\dell\Desktop\Hexo\node_modules\nunjucks\src\environment.js:619:9
    at Template.root [as rootRenderFunc] (eval at _compile (C:\Users\dell\Desktop\H                                                                                                                               exo\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:78:1)
    at Template.getExported (C:\Users\dell\Desktop\Hexo\node_modules\nunjucks\src\e                                                                                                                               nvironment.js:615:10)
    at eval (eval at _compile (C:\Users\dell\Desktop\Hexo\node_modules\nunjucks\src                                                                                                                               \environment.js:637:18), <anonymous>:18:5)
    at createTemplate (C:\Users\dell\Desktop\Hexo\node_modules\nunjucks\src\environ                                                                                                                               ment.js:315:9)
    at handle (C:\Users\dell\Desktop\Hexo\node_modules\nunjucks\src\environment.js:                                                                                                                               327:11)
    at C:\Users\dell\Desktop\Hexo\node_modules\nunjucks\src\environment.js:339:9
    at next (C:\Users\dell\Desktop\Hexo\node_modules\nunjucks\src\lib.js:280:7)
    at Object.asyncIter (C:\Users\dell\Desktop\Hexo\node_modules\nunjucks\src\lib.j                                                                                                                               s:286:3)
    at Environment.getTemplate (C:\Users\dell\Desktop\Hexo\node_modules\nunjucks\sr                                                                                                                               c\environment.js:321:9)
    at eval (eval at _compile (C:\Users\dell\Desktop\Hexo\node_modules\nunjucks\src                                                                                                                               \environment.js:637:18), <anonymous>:16:5)
    at createTemplate (C:\Users\dell\Desktop\Hexo\node_modules\nunjucks\src\environ                                                                                                                               ment.js:315:9)

**Comment by yansheng836** [comment]
@xjywhu I also encountered this problem, I want to know how you solve it

**Comment by dragonlayout** [comment]
I find that tags/v7.7.0 has no such error, and #1346 revert this change will work fine.
Hoping someone can fix this.

**Comment by xjywhu** [comment]
I don't know how to solve the problem, but you can use the tags/v7.7.0，that version can run successfully.&nbsp;



---原始邮件---
发件人: "荷塘月色"<notifications@github.com&gt;
发送时间: 2020年2月8日(星期六) 下午2:53
收件人: "theme-next/hexo-theme-next"<hexo-theme-next@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"xjywhu"<727308015@qq.com&gt;;
主题: Re: [theme-next/hexo-theme-next] hexo s后访问网站出现TypeError: Cannot read property 'path' of undefined (#1371)



@xjywhu I also encountered this problem, I want to know how you solve it

**Comment by xjywhu** [comment]
Thanks for your answering.&nbsp;



---原始邮件---
发件人: "Long Chen"<notifications@github.com&gt;
发送时间: 2020年2月8日(星期六) 晚上8:30
收件人: "theme-next/hexo-theme-next"<hexo-theme-next@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"xjywhu"<727308015@qq.com&gt;;
主题: Re: [theme-next/hexo-theme-next] hexo s后访问网站出现TypeError: Cannot read property 'path' of undefined (#1371)



I find that tags/v7.7.0 has no such error, and #1346 revert this change will work fine.
 Hoping someone can fix this.

**Comment by yansheng836** [comment]
Thank you!
