### ISSUE TITLE
ERROR Template render error: Template render error; TypeError: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by dragonlayout** [theme-next/hexo-theme-next#1373]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have reviewed [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md), especially the [Before Submitting An Issue](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md#before-submitting-an-issue) part.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Expected behavior 
git clone https://github.com/theme-next/hexo-theme-next themes/next, 然后执行 npx hexo g, 没有报错出现.

## Actual behavior 

执行 npx hexo g 之后出现报错信息
```bash
npx hexo g    
INFO  Start processing
INFO  Files loaded in 620 ms
ERROR Template render error: Template render error: (/Users/chenlong/Documents/Blog/Notes/hexo_demo/themes/next/layout/post.swig) [Line 3, Column 12]
  Template render error: (/Users/chenlong/Documents/Blog/Notes/hexo_demo/themes/next/layout/_partials/head/head.swig) [Line 60, Column 14]
  TypeError: Cannot read property 'path' of undefined
Template render error: (/Users/chenlong/Documents/Blog/Notes/hexo_demo/themes/next/layout/post.swig) [Line 3, Column 12]
  Template render error: (/Users/chenlong/Documents/Blog/Notes/hexo_demo/themes/next/layout/_partials/head/head.swig) [Line 60, Column 14]
  TypeError: Cannot read property 'path' of undefined
    at Object._prettifyError (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/lib.js:36:11)
    at /Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:567:19
    at Template.root [as rootRenderFunc] (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:186:3)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:35:16)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:30:46)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:30:86)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:26:46)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:26:86)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:22:46)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:22:84)
    at /Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:619:9
    at Template.root [as rootRenderFunc] (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:78:1)
    at Template.getExported (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:615:10)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:18:5)
    at createTemplate (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:315:9)
    at handle (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:327:11)
ERROR Template render error: Template render error: Template render error: (/Users/chenlong/Documents/Blog/Notes/hexo_demo/themes/next/layout/archive.swig) [Line 3, Column 12]
  Template render error: (/Users/chenlong/Documents/Blog/Notes/hexo_demo/themes/next/layout/_partials/head/head.swig) [Line 60, Column 14]
  TypeError: Cannot read property 'path' of undefined
Template render error: (/Users/chenlong/Documents/Blog/Notes/hexo_demo/themes/next/layout/archive.swig) [Line 3, Column 12]
  Template render error: (/Users/chenlong/Documents/Blog/Notes/hexo_demo/themes/next/layout/_partials/head/head.swig) [Line 60, Column 14]
  TypeError: Cannot read property 'path' of undefined
    at Object._prettifyError (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/lib.js:36:11)
    at /Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:567:19
    at Template.root [as rootRenderFunc] (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:186:3)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:41:16)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:36:46)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:36:86)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:32:46)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:32:86)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:28:46)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:28:84)
    at /Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:619:9
    at Template.root [as rootRenderFunc] (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:78:1)
    at Template.getExported (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:615:10)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:24:5)
    at createTemplate (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:315:9)
    at handle (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:327:11)
ERROR Template render error: Template render error: Template render error: (/Users/chenlong/Documents/Blog/Notes/hexo_demo/themes/next/layout/archive.swig) [Line 3, Column 12]
  Template render error: (/Users/chenlong/Documents/Blog/Notes/hexo_demo/themes/next/layout/_partials/head/head.swig) [Line 60, Column 14]
  TypeError: Cannot read property 'path' of undefined
Template render error: (/Users/chenlong/Documents/Blog/Notes/hexo_demo/themes/next/layout/archive.swig) [Line 3, Column 12]
  Template render error: (/Users/chenlong/Documents/Blog/Notes/hexo_demo/themes/next/layout/_partials/head/head.swig) [Line 60, Column 14]
  TypeError: Cannot read property 'path' of undefined
    at Object._prettifyError (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/lib.js:36:11)
    at /Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:567:19
    at Template.root [as rootRenderFunc] (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:186:3)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:41:16)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:36:46)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:36:86)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:32:46)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:32:86)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:28:46)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:28:84)
    at /Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:619:9
    at Template.root [as rootRenderFunc] (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:78:1)
    at Template.getExported (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:615:10)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:24:5)
    at Environment.getTemplate (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:279:9)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:22:5)
ERROR Template render error: Template render error: Template render error: (/Users/chenlong/Documents/Blog/Notes/hexo_demo/themes/next/layout/archive.swig) [Line 3, Column 12]
  Template render error: (/Users/chenlong/Documents/Blog/Notes/hexo_demo/themes/next/layout/_partials/head/head.swig) [Line 60, Column 14]
  TypeError: Cannot read property 'path' of undefined
Template render error: (/Users/chenlong/Documents/Blog/Notes/hexo_demo/themes/next/layout/archive.swig) [Line 3, Column 12]
  Template render error: (/Users/chenlong/Documents/Blog/Notes/hexo_demo/themes/next/layout/_partials/head/head.swig) [Line 60, Column 14]
  TypeError: Cannot read property 'path' of undefined
    at Object._prettifyError (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/lib.js:36:11)
    at /Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:567:19
    at Template.root [as rootRenderFunc] (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:186:3)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:41:16)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:36:46)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:36:86)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:32:46)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:32:86)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:28:46)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:28:84)
    at /Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:619:9
    at Template.root [as rootRenderFunc] (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:78:1)
    at Template.getExported (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:615:10)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:24:5)
    at Environment.getTemplate (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:279:9)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:22:5)
ERROR Template render error: Template render error: (/Users/chenlong/Documents/Blog/Notes/hexo_demo/themes/next/layout/index.swig) [Line 3, Column 12]
  Template render error: (/Users/chenlong/Documents/Blog/Notes/hexo_demo/themes/next/layout/_partials/head/head.swig) [Line 60, Column 14]
  TypeError: Cannot read property 'path' of undefined
Template render error: (/Users/chenlong/Documents/Blog/Notes/hexo_demo/themes/next/layout/index.swig) [Line 3, Column 12]
  Template render error: (/Users/chenlong/Documents/Blog/Notes/hexo_demo/themes/next/layout/_partials/head/head.swig) [Line 60, Column 14]
  TypeError: Cannot read property 'path' of undefined
    at Object._prettifyError (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/lib.js:36:11)
    at /Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:567:19
    at Template.root [as rootRenderFunc] (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:186:3)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:35:16)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:30:46)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:30:86)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:26:46)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:26:86)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:22:46)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:22:84)
    at /Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:619:9
    at Template.root [as rootRenderFunc] (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:78:1)
    at Template.getExported (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:615:10)
    at eval (eval at _compile (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:18:5)
    at createTemplate (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:315:9)
    at handle (/Users/chenlong/Documents/Blog/Notes/hexo_demo/node_modules/nunjucks/src/environment.js:327:11)
INFO  Generated: index.html
INFO  Generated: archives/index.html
INFO  Generated: images/apple-touch-icon-next.png
INFO  Generated: images/cc-by-nc-sa.svg
INFO  Generated: images/cc-by-nc.svg
INFO  Generated: images/cc-by-sa.svg
INFO  Generated: images/cc-by-nd.svg
INFO  Generated: images/avatar.gif
INFO  Generated: images/cc-by.svg
INFO  Generated: images/cc-by-nc-nd.svg
INFO  Generated: images/cc-zero.svg
INFO  Generated: images/favicon-32x32-next.png
INFO  Generated: images/logo.svg
INFO  Generated: images/favicon-16x16-next.png
INFO  Generated: images/quote-r.svg
INFO  Generated: archives/2020/02/index.html
INFO  Generated: images/quote-l.svg
INFO  Generated: archives/2020/index.html
INFO  Generated: images/algolia_logo.svg
INFO  Generated: lib/font-awesome/HELP-US-OUT.txt
INFO  Generated: js/algolia-search.js
INFO  Generated: lib/velocity/velocity.ui.min.js
INFO  Generated: css/main.css
INFO  Generated: js/bookmark.js
INFO  Generated: js/motion.js
INFO  Generated: js/next-boot.js
INFO  Generated: js/utils.js
INFO  Generated: js/local-search.js
INFO  Generated: lib/font-awesome/bower.json
INFO  Generated: lib/velocity/velocity.min.js
INFO  Generated: lib/anime.min.js
INFO  Generated: lib/font-awesome/fonts/fontawesome-webfont.woff
INFO  Generated: lib/font-awesome/fonts/fontawesome-webfont.woff2
INFO  Generated: lib/font-awesome/css/font-awesome.css.map
INFO  Generated: 2020/02/08/hello-world/index.html
INFO  Generated: lib/font-awesome/fonts/fontawesome-webfont.eot
INFO  Generated: js/schemes/muse.js
INFO  Generated: lib/font-awesome/css/font-awesome.css
INFO  Generated: lib/font-awesome/css/font-awesome.min.css
INFO  Generated: js/schemes/pisces.js
INFO  40 files generated in 490 ms
```
- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. npx hexo init hexo_demo && cd hexo_demo
2. 修改 _config.yml theme: next, 保存
3. npx hexo g

### Node.js and NPM Information

```
node -v && npm -v
v12.6.0
6.9.0
```

### Package dependencies Information

```
npm ls --depth 0
/Users/chenlong
└── (empty)
```

### Hexo Configuration

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo
subtitle: ''
description: ''
keywords:
author: John Doe
language: en
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include: []
exclude: []
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: ''

```

### NexT Configuration

```yml
tags/v7.7.1 默认配置,无修改
```

## Other Information 
我尝试切换 Next 到 tags/v7.7.0 发现 `npx hexo g` 可以正常运行 无报错信息, 怀疑是 #1346 导致到问题.
在  tags/v7.7.1 修改 themes/next/layout/_partials/head/head.swig 的文件为  tags/v7.7.0 的内容, `npx hexo g` 亦可以正常运行 无报错信息

**Comment by jiangtj** [comment]
确定在 tags/v7.7.1 中遇到错误？  tags/v7.7.1 并没包含 #1346

我没有复现，能不能提供博客源码

**Comment by jiangtj** [comment]
#1371  似乎是一样问题

**Comment by stevenjoezhang** [comment]
7.7.0和7.7.1之间对模版的改动：
https://github.com/theme-next/hexo-theme-next/commit/726ce63d8478039ee4f549bedea74fd55d1a112d
https://github.com/theme-next/hexo-theme-next/commit/c6ed63130700d5ca099aefef2f425fc8c67989e2

**Comment by dragonlayout** [comment]
@jiangtj @stevenjoezhang  不好意思, 我看错了, 我本地复现的是 v7.7.0 和 master 分支, 不是 v7.7.1。

**Comment by jiangtj** [comment]
@dragonlayout 你能帮助测试下`fix-search-path`分支是否存在这个问题？

Can you help test if the problem exists with `fix-search-path` branch?

**Comment by dragonlayout** [comment]
> @dragonlayout 你能帮助测试下`fix-search-path`分支是否存在这个问题？
> 
> Can you help test if the problem exists with `fix-search-path` branch?

`fix-search-path` 运行 `npx hexo g`, `npx hexo s` 均正常, 无报错
