### ISSUE TITLE
reminder error

### ISSUE THREAD

**Issue by bmyjacks** [theme-next/hexo-theme-next#1451]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
开启`reminder`来提醒更新主题

## Actual behavior 
报错
```bash
ERROR Failed to detect version info. Error message:
ERROR Cannot read property 'replace' of undefined
TypeError: Cannot read property 'replace' of undefined
    at IncomingMessage.<anonymous> (D:\blog\themes\next\scripts\events\index.js:28:49)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

- Links to demo site with this issue: 
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. 在`source/_data/next.yml`中设置`reminder: true`

### Node.js and NPM Information

```bash
node: v13.12.0
npm: 6.14.4
```

### Package dependencies Information

```json
+-- acorn@7.1.1
+-- hawk@7.0.10
+-- hexo@4.2.0
+-- hexo-algolia@1.3.1
+-- hexo-autonofollow@1.0.1
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-baidu-sitemap@0.1.6
+-- hexo-generator-category@1.0.0
+-- hexo-generator-feed@2.2.0
+-- hexo-generator-index@1.0.0
+-- hexo-generator-sitemap@2.0.0
+-- hexo-generator-tag@1.0.0
+-- hexo-neat@1.0.4
+-- hexo-related-popular-posts@4.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@2.0.0
+-- hexo-renderer-stylus@1.1.0
+-- hexo-server@1.0.0
+-- hexo-symbols-count-time@0.7.1
+-- hoek@6.1.3
`-- minimist@1.2.5
```

### Hexo Configuration

```yml

```

### NexT Configuration

```yml

```

## Other Information 
![image](https://user-images.githubusercontent.com/38985658/78472273-0148ac00-776a-11ea-9b95-7f090f509c61.png)

**Comment by bmyjacks** [comment]
在v7.7.2中是正常的，但是在v7.8.0中就报错了

**Comment by bmyjacks** [comment]
重新安装好了
