### ISSUE TITLE
关于/theme-next/next-util工具

### ISSUE THREAD

**Issue by aixiu** [theme-next/hexo-theme-next#1497]
@stevenjoezhang 首先感谢你的工作，希望你帮我看看是什么原因。
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
```
npm install next-util
```
为了证明linux和win7下的差异，我先在LINUX下试验得如下结果。
使用命令在博客根目安装，得到正常的目录结构。如：
![image](https://user-images.githubusercontent.com/8064012/81286493-bcc76d80-9093-11ea-8256-56724939edfd.png)

## Actual behavior 

```
npm install next-util
```
在WIN7下同样在博客根目录安装。
插件目录为：
![image](https://user-images.githubusercontent.com/8064012/81286687-087a1700-9094-11ea-9c35-e8107b447244.png)

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

### Node.js and NPM Information

```
$ node -v && npm -v
v12.16.1
6.13.4
```

### Package dependencies Information

```

```

### Hexo Configuration

```yml

```

### NexT Configuration

```yml

```

## Other Information 
请问，为什么WIN下安装好插件后，\node_modules\next-util  包里只有一个package.json
因为使用了其它的插件，依赖此插件，hexo clean等操作都会报错。
```
$ hexo clean
ERROR Plugin load failed: hexo-next-title
Error: Cannot find module 'E:\My_blog\node_modules\next-util\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:316:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:705:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:969:27)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (E:\My_blog\node_modules\hexo\lib\hexo\index.js:280:23)
    at E:\My_blog\node_modules\hexo-next-title\index.js:5:14
    at E:\My_blog\node_modules\hexo\lib\hexo\index.js:293:14
    at tryCatcher (E:\My_blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\My_blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\My_blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\My_blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\My_blog\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (E:\My_blog\node_modules\bluebird\js\release\promise.js:673:18)
    at Promise._resolveCallback (E:\My_blog\node_modules\bluebird\js\release\promise.js:466:57)
    at Promise._settlePromiseFromHandler (E:\My_blog\node_modules\bluebird\js\release\promise.js:559:17)
    at Promise._settlePromise (E:\My_blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\My_blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\My_blog\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (E:\My_blog\node_modules\bluebird\js\release\promise.js:673:18)
    at E:\My_blog\node_modules\bluebird\js\release\nodeback.js:42:21
    at E:\My_blog\node_modules\graceful-fs\graceful-fs.js:115:16
ERROR Plugin load failed: hexo-next-utteranc
Error: Cannot find module 'E:\My_blog\node_modules\next-util\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:316:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:705:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:969:27)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (E:\My_blog\node_modules\hexo\lib\hexo\index.js:280:23)
    at E:\My_blog\node_modules\hexo-next-utteranc\index.js:5:14
    at E:\My_blog\node_modules\hexo\lib\hexo\index.js:293:14
    at tryCatcher (E:\My_blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\My_blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\My_blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\My_blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\My_blog\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (E:\My_blog\node_modules\bluebird\js\release\promise.js:673:18)
    at Promise._resolveCallback (E:\My_blog\node_modules\bluebird\js\release\promise.js:466:57)
    at Promise._settlePromiseFromHandler (E:\My_blog\node_modules\bluebird\js\release\promise.js:559:17)
    at Promise._settlePromise (E:\My_blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\My_blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\My_blog\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (E:\My_blog\node_modules\bluebird\js\release\promise.js:673:18)
    at E:\My_blog\node_modules\bluebird\js\release\nodeback.js:42:21
    at E:\My_blog\node_modules\graceful-fs\graceful-fs.js:115:16
INFO  Deleted database.
INFO  Deleted public folder.

```

**Comment by 799953468** [comment]
安装的log有嘛

**Comment by aixiu** [comment]
@799953468 在哪查看log

**Comment by 799953468** [comment]
用npm i 好像才有 debug.log

**Comment by aixiu** [comment]
```
$ npm install next-util
npm WARN registry Using stale data from https://registry.npm.taobao.org/ because the host is inaccessible -- are you offline?
npm WARN registry Using stale data from https://registry.npm.taobao.org/ due to a request error during revalidation.
npm WARN rollback Rolling back node-pre-gyp@0.14.0 failed (this is probably harmless): EPERM: operation not permitted, lstat 'E:\My_blog\node_modules\hexo-related-popular-posts\node_modules\fsevents\node_modules'
npm WARN quicklink@2.0.0-beta requires a peer of react@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN quicklink@2.0.0-beta requires a peer of react-dom@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules\hexo-related-popular-posts\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules\hexo-generator-baidu-sitemap\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ next-util@1.0.0
updated 1 package in 9.528s

```
只有这个，好像说是需要安装npm WARN quicklink@2.0.0-beta requires a peer of react@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN quicklink@2.0.0-beta requires a peer of react-dom@^16.8.0 but none is installed. You must install peer dependencies yourself.

但是这个插件库没提这些问题

**Comment by 799953468** [comment]
试试yarn

**Comment by aixiu** [comment]
其实这问题，出现好久了，2019年底就现，后来我是把https://github.com/theme-next/next-util/blob/master/index.js 这个文件复制一份，到WIN系统下BLOG的E:\My_blog\node_modules\next-util
目录，然后就正常了，问题是解决了，但是我也不知道为什么

**Comment by aixiu** [comment]
@799953468 感谢，yarn没用过，还在看

**Comment by stevenjoezhang** [comment]
目测是你使用了淘宝源的问题。

**Comment by aixiu** [comment]
@stevenjoezhang 那还不能用这个源了？我换个试试

**Comment by stevenjoezhang** [comment]
已向淘宝源反馈此问题 https://github.com/cnpm/npm.taobao.org/issues/63
并在更新说明中警告用户使用淘宝源造成的一切后果自负
