### ISSUE TITLE
设置 related_posts的enable为true 时, 出现 TypeError: Cannot read property 'replace' of null 的问题

### ISSUE THREAD

**Issue by hui-shao** [theme-next/hexo-theme-next#1498]
## Issue Checklist

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
正常地生成站点，而没有报错信息

## Actual behavior 
因为站点还在配置中，目前只在本地测试，暂时没上传.

报错信息如下（节选, 在生成每个文章页面时都会重复同类错误）：
```tex
ERROR Render HTML failed: 2020/05/07/hexo-code-block/index.html
TypeError: Cannot read property 'replace' of null
    at Hexo.externalLinkFilter (F:\GitHub\MyBlog\hui-shao.github.io\node_modules\hexo\lib\plugins\filter\after_render\external_link.js:22:15)
    at Hexo.tryCatcher (F:\GitHub\MyBlog\hui-shao.github.io\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (F:\GitHub\MyBlog\hui-shao.github.io\node_modules\bluebird\js\release\method.js:15:34)
    at F:\GitHub\MyBlog\hui-shao.github.io\node_modules\hexo\lib\extend\filter.js:62:52
    at tryCatcher (F:\GitHub\MyBlog\hui-shao.github.io\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (F:\GitHub\MyBlog\hui-shao.github.io\node_modules\bluebird\js\release\reduce.js:166:18)
    at Object.gotAccum (F:\GitHub\MyBlog\hui-shao.github.io\node_modules\bluebird\js\release\reduce.js:155:25)
    at Object.tryCatcher (F:\GitHub\MyBlog\hui-shao.github.io\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (F:\GitHub\MyBlog\hui-shao.github.io\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (F:\GitHub\MyBlog\hui-shao.github.io\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (F:\GitHub\MyBlog\hui-shao.github.io\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (F:\GitHub\MyBlog\hui-shao.github.io\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (F:\GitHub\MyBlog\hui-shao.github.io\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (F:\GitHub\MyBlog\hui-shao.github.io\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (F:\GitHub\MyBlog\hui-shao.github.io\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
```

## Steps to reproduce the behavior
1. 修改NexT `_config.yml` 里面的 related_posts的enable 为true
2. 执行 `hexo clean && hexo g`

注：只要把 1 中的设为 false 即可正常进行生成

### Node.js and NPM Information
```
$ node -v && npm -v

v12.16.1
6.13.4
```

### Package dependencies Information

```
+-- css-select@2.1.0
+-- hexo@4.2.0
+-- hexo-deployer-git@2.1.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@1.0.0
+-- hexo-generator-search@2.4.0
+-- hexo-generator-sitemap@2.0.0
+-- hexo-generator-tag@1.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@2.0.0
+-- hexo-renderer-stylus@1.1.0
+-- hexo-server@1.0.0
+-- lodash@4.17.15
`-- lodash.assign@4.2.0

```

### Hexo Configuration

始终没有修改过

### NexT Configuration

```yml
related_posts:
  enable: enable
```

## Other Information 
无

**Comment by hui-shao** [comment]
问题解决了，是我的问题。没安装依赖包。不好意思.
