### ISSUE TITLE
hexo-leancloud-counter-security--Errors

### ISSUE THREAD

**Issue by aixiu** [theme-next/hexo-theme-next#163]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
node -v
v8.9.4

npm -v
5.7.1

```

### Package dependencies Information

```
 cat package.json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.6.0"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-baidu-sitemap": "^0.1.2",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-leancloud-counter-security": "^1.2.0",
    "hexo-neat": "^1.0.4",
    "hexo-related-popular-posts": "^3.0.1",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0",
    "hexo-symbols-count-time": "^0.3.2"
  }
}


```

#### Hexo version

```
hexo -v
hexo: 3.6.0
hexo-cli: 1.1.0
os: Windows_NT 6.1.7601 win32 x64
http_parser: 2.7.0
node: 8.9.4
v8: 6.1.534.50
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2n
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b

```

#### Hexo Configuration

```yml
# Show number of visitors to each article.
# You can visit https://leancloud.cn get AppID and AppKey.
leancloud_visitors:
  enable: true
  app_id: ************DX9VUB-gzGzoHsz
  app_key: YzW4************AdcGdYueo
  # Dependencies: https://github.com/theme-next/hexo-leancloud-counter-security
  security: true
  betterPerformance: true
```

### NexT Information

**NexT Version:**

- [x] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [x] Gemini

#### NexT Configuration:

```yml

```

### Other Information 
```
TypeError: Cannot read property 'enable_sync' of undefined
    at Hexo.generate_post_list (E:\myblog-hexo\node_modules\hexo-leancloud-count                                                                                                                                                                                               er-security\index.js:10:43)
    at Hexo.tryCatcher (E:\myblog-hexo\node_modules\bluebird\js\release\util.js:                                                                                                                                                                                               16:23)
    at Hexo.<anonymous> (E:\myblog-hexo\node_modules\bluebird\js\release\method.                                                                                                                                                                                               js:15:34)
    at Promise.map.key (E:\myblog-hexo\node_modules\hexo\lib\hexo\index.js:336:2                                                                                                                                                                                               6)
    at tryCatcher (E:\myblog-hexo\node_modules\bluebird\js\release\util.js:16:23                                                                                                                                                                                               )
    at MappingPromiseArray._promiseFulfilled (E:\myblog-hexo\node_modules\bluebi                                                                                                                                                                                               rd\js\release\map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (E:\myblog-hexo\node_modules\bl                                                                                                                                                                                               uebird\js\release\promise_array.js:114:31)
    at MappingPromiseArray.init (E:\myblog-hexo\node_modules\bluebird\js\release                                                                                                                                                                                               \promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (E:\myblog-hexo\node_modules\bluebird\js\r                                                                                                                                                                                               elease\map.js:30:10)
    at Async._drainQueue (E:\myblog-hexo\node_modules\bluebird\js\release\async.                                                                                                                                                                                               js:138:12)
    at Async._drainQueues (E:\myblog-hexo\node_modules\bluebird\js\release\async                                                                                                                                                                                               .js:143:10)
    at Immediate.Async.drainQueues (E:\myblog-hexo\node_modules\bluebird\js\rele                                                                                                                                                                                               ase\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

**Comment by LEAFERx** [comment]
Have u make config in site _config.yml？

**Comment by aixiu** [comment]
@LEAFERx Thank you for solving my problem.

**Comment by LEAFERx** [comment]
No problem. Next time please issue on hexo-leancloud-counter-security repo

**Comment by aixiu** [comment]
ok.

**Comment by Devopswalker** [comment]
How can I solve this problem? I did not configure leancloud_visitors.
