### ISSUE TITLE
Template render error: Error: template not found: _components/algolia-search/assets.swig

### ISSUE THREAD

**Issue by zhuoresume** [theme-next/hexo-theme-next#286]
### I agree and want to create new issue 

- [X]  Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X]  Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X]  And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Actual behavior 
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/do                                                                                                                                  cs/troubleshooting.html
Template render error: Error: template not found: _components/algolia-search/ass                                                                                                                                  ets.swig
    at Object._prettifyError (D:\temp\blog\node_modules\nunjucks\src\lib.js:35:1                                                                                                                                  1)
    at D:\temp\blog\node_modules\nunjucks\src\environment.js:547:19
    at Template.root [as rootRenderFunc] (eval at _compile (D:\temp\blog\node_mo                                                                                                                                  dules\nunjucks\src\environment.js:617:18), <anonymous>:125:3)
    at Template.render (D:\temp\blog\node_modules\nunjucks\src\environment.js:54                                                                                                                                  0:10)
    at Environment.renderString (D:\temp\blog\node_modules\nunjucks\src\environm                                                                                                                                  ent.js:364:17)
    at Promise (D:\temp\blog\node_modules\hexo\lib\extend\tag.js:66:9)
    at Promise._execute (D:\temp\blog\node_modules\bluebird\js\release\debuggabi                                                                                                                                  lity.js:303:9)
    at Promise._resolveFromExecutor (D:\temp\blog\node_modules\bluebird\js\relea                                                                                                                                  se\promise.js:483:18)
    at new Promise (D:\temp\blog\node_modules\bluebird\js\release\promise.js:79:                                                                                                                                  10)
    at Tag.render (D:\temp\blog\node_modules\hexo\lib\extend\tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (D:\temp\blog\node_modules\hexo\lib\hex                                                                                                                                  o\post.js:230:16)
    at Promise.then.then.result (D:\temp\blog\node_modules\hexo\lib\hexo\render.                                                                                                                                  js:65:19)
    at tryCatcher (D:\temp\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\temp\blog\node_modules\bluebird\js\                                                                                                                                  release\promise.js:512:31)
    at Promise._settlePromise (D:\temp\blog\node_modules\bluebird\js\release\pro                                                                                                                                  mise.js:569:18)
    at Promise._settlePromise0 (D:\temp\blog\node_modules\bluebird\js\release\pr                                                                                                                                  omise.js:614:10)
    at Promise._settlePromises (D:\temp\blog\node_modules\bluebird\js\release\pr                                                                                                                                  omise.js:693:18)
    at Async._drainQueue (D:\temp\blog\node_modules\bluebird\js\release\async.js                                                                                                                                  :133:16)
    at Async._drainQueues (D:\temp\blog\node_modules\bluebird\js\release\async.j                                                                                                                                  s:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\temp\blog\node_modules\                                                                                                                                  bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)

### Steps to reproduce the behavior 
1. after updated the latest Theme-Next
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
v8.9.1

5.5.1
```
### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.7.1"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-server": "^0.2.0"
  },
  "devDependencies": {
    "hexo-util": "^0.6.3"
  }
}

```

#### Hexo version

```
hexo: 3.7.1
hexo-cli: 1.1.0
os: Windows_NT 10.0.16299 win32 x64
http_parser: 2.7.0
node: 8.9.1
v8: 6.1.534.47
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2m
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [X]  Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [X]  Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

**Comment by sli1989** [comment]
Followed [this instruction](https://github.com/theme-next/hexo-theme-next/blob/master/docs/ALGOLIA-SEARCH.md)?
Need your detailed steps to reproduce.

**Comment by zhuoresume** [comment]
Solved, thanks!
it caused by 
'''
{% codeblock %}
{% include '_components/algolia-search/assets.swig' %}
{% endcodeblock %}
'''
That an { } cannot insert into another { }block.
