### ISSUE TITLE
TypeError: Cannot read property 'enable_sync' of undefined

### ISSUE THREAD

**Issue by imcco** [theme-next/hexo-theme-next#297]
### I agree and want to create new issue 

- [x ] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [ ] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [ ] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
Successful deployment

### Actual behavior 
$ hexo g
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'enable_sync' of undefined
    at Hexo.generate_post_list (F:\blog\node_modules\hexo-leancloud-counter-security\index.js:114:42)
    at Hexo.tryCatcher (F:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (F:\blog\node_modules\bluebird\js\release\method.js:15:34)
    at Promise.map.key (F:\blog\node_modules\hexo\lib\hexo\index.js:336:26)
    at tryCatcher (F:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (F:\blog\node_modules\bluebird\js\release\map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (F:\blog\node_modules\bluebird\js\release\promise_array.js:114:31)
    at MappingPromiseArray.init (F:\blog\node_modules\bluebird\js\release\promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (F:\blog\node_modules\bluebird\js\release\map.js:30:10)
    at Async._drainQueue (F:\blog\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (F:\blog\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (F:\blog\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
$ hexo g
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'enable_sync' of undefined
    at Hexo.generate_post_list (F:\blog\node_modules\hexo-leancloud-counter-security\index.js:114:42)
    at Hexo.tryCatcher (F:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (F:\blog\node_modules\bluebird\js\release\method.js:15:34)
    at Promise.map.key (F:\blog\node_modules\hexo\lib\hexo\index.js:336:26)
    at tryCatcher (F:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (F:\blog\node_modules\bluebird\js\release\map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (F:\blog\node_modules\bluebird\js\release\promise_array.js:114:31)
    at MappingPromiseArray.init (F:\blog\node_modules\bluebird\js\release\promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (F:\blog\node_modules\bluebird\js\release\map.js:30:10)
    at Async._drainQueue (F:\blog\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (F:\blog\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (F:\blog\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)

```

### Package dependencies Information

```

```

#### Hexo version

```

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [x ] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [x ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

**Comment by sli1989** [comment]
Please provide the detailed steps to reproduce. And check carefully with the [instruction](https://github.com/theme-next/hexo-theme-next/blob/master/docs/LEANCLOUD-COUNTER-SECURITY.md).

**Comment by imcco** [comment]
I think I know what's going on, thanks

**Comment by sli1989** [comment]
Well, if there is no problem, you can close the issue.
