### ISSUE TITLE
为什么站点名称和说明不能是中文啊？

### ISSUE THREAD

**Issue by shuimaizi** [theme-next/hexo-theme-next#379]
# Site
title: Garden
subtitle:
description: Live in 
author: Shuimaizi
language: zh-Hans
timezone: Asia/Beijing

搞了老半天， title,subtitle，description, author， 都不能写中文啊， 写了中文就报错，或者就乱码，要怎么办啊？

**Comment by shuimaizi** [comment]
在站点配置的config.yml里面，也不能写中文， 写了，出来就是乱码。该怎么办啊？
# Reward
reward_comment: 感谢支持！

**Comment by Raincal** [comment]
我试了下，没有问题
你看下你的文件编码格式是不是 UTF-8

**Comment by shuimaizi** [comment]
我是Mac，我按照网上说的， 打开文本编辑，然后偏好设置---打开和存储文件都改成了，utf-8的格式。 但还是不行啊，���ӡ����������ҵ�ߣ���� 老是显示成这样。

**Comment by shuimaizi** [comment]
我改成中文的，报错。 我就改回英文的， 但还是报错。到底要怎么办啊。。？？

FATAL the stream contains non-printable characters at line 9, column 21:
    author: Shuimaizi
                        ^
YAMLException: the stream contains non-printable characters at line 9, column 21:
    author: Shuimaizi
                        ^
    at generateError (/Users/maggie/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:165:10)
    at throwError (/Users/maggie/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:171:9)
    at captureSegment (/Users/maggie/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:259:7)
    at readPlainScalar (/Users/maggie/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:506:3)
    at composeNode (/Users/maggie/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1348:20)
    at readBlockMapping (/Users/maggie/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1062:11)
    at composeNode (/Users/maggie/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1332:12)
    at readDocument (/Users/maggie/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1492:3)
    at loadDocuments (/Users/maggie/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1548:5)
    at Object.load (/Users/maggie/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1569:19)
    at Hexo.yamlHelper (/Users/maggie/hexo/node_modules/hexo/lib/plugins/renderer/yaml.js:7:15)
    at Hexo.tryCatcher (/Users/maggie/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/maggie/hexo/node_modules/bluebird/js/release/method.js:15:34)
    at Promise.then.text (/Users/maggie/hexo/node_modules/hexo/lib/hexo/render.js:61:21)
    at tryCatcher (/Users/maggie/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/maggie/hexo/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/maggie/hexo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/maggie/hexo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/maggie/hexo/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/maggie/hexo/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/maggie/hexo/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/maggie/hexo/node_modules/bluebird/js/release/async.js:17:14)

**Comment by shuimaizi** [comment]
终于搞定了。既然报错，我就改成英文名称了，还是报错，我就删掉，先空着。 然后就可以预览了，然后都改成我想要的中文，然后就直接上传到网上去了。 然后都ok了。。
搞定

**Comment by stevenjoezhang** [comment]
改动之后执行一下`hexo s`应该能解决不少问题
