### ISSUE TITLE
worldcount报错

### ISSUE THREAD

**Issue by wubmu** [theme-next/hexo-theme-next#544]
# Post wordcount display settings
# Dependencies: https://github.com/willin/hexo-wordcount
post_wordcount:
  item_text: true
  wordcount: true
  min2read: true

error:

ERROR Theme config load failed.
ERROR Process failed: _config.yml
YAMLException: duplicated mapping key at line 1079, column 1:
    post_wordcount:
    ^
    at generateError (D:\HEXO\node_modules\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:162:10)
    at throwError (D:\HEXO\node_modules\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:168:9)
    at storeMappingPair (D:\HEXO\node_modules\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:305:7)
    at readBlockMapping (D:\HEXO\node_modules\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1065:9)
    at composeNode (D:\HEXO\node_modules\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1326:12)
    at readDocument (D:\HEXO\node_modules\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1488:3)
    at loadDocuments (D:\HEXO\node_modules\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1544:5)
    at Object.load (D:\HEXO\node_modules\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1561:19)
    at Hexo.yamlHelper (D:\HEXO\node_modules\hexo\lib\plugins\renderer\yaml.js:7:15)
    at Hexo.tryCatcher (D:\HEXO\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (D:\HEXO\node_modules\hexo\node_modules\bluebird\js\release\method.js:15:34)
    at D:\HEXO\node_modules\hexo\lib\hexo\render.js:61:21
    at tryCatcher (D:\HEXO\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\HEXO\node_modules\hexo\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (D:\HEXO\node_modules\hexo\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (D:\HEXO\node_modules\hexo\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (D:\HEXO\node_modules\hexo\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (D:\HEXO\node_modules\hexo\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (D:\HEXO\node_modules\hexo\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\HEXO\node_modules\hexo\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
INFO  Files loaded in 1.05 s
Unhandled rejection Error: ENOENT: no such file or directory, open 'D:\HEXO\themes\next\layout\_scripts\schemes\.swig'
    at Object.openSync (fs.js:439:3)
    at Object.readFileSync (fs.js:344:35)

主题文件已经通过了：YAML Lint

**Comment by wubmu** [comment]
post_wordcount:
  item_text: true
  wordcount: true
  min2read: true

格式是对的

**Comment by stevenjoezhang** [comment]
wordcount插件是否为`hexo-symbols-count-time`？
然后检查`_config.yml`是否有重复内容

**Comment by wubmu** [comment]
不是hexo-wordcount插件么？？

**Comment by stevenjoezhang** [comment]
hexo-wordcount插件淘汰了，你可以用npm安装这个，然后重新配置：https://github.com/theme-next/hexo-symbols-count-time

**Comment by stevenjoezhang** [comment]
I'll take your silence as a sign the problem is solved
