### ISSUE TITLE
瞎操作导致的

### ISSUE THREAD

**Issue by Flower233pks** [theme-next/hexo-theme-next#999]
### I agree and want to create new issue 

- [ ] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [ ] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

实际上在`themes-next`目录下只是`git stash`, `git pull`, `git stash pop`了一下

### Actual behavior 

`hexo s`报错：
>ERROR Process failed: layout/index.swig
Error: Unexpected end of tag "macro" on line 455 in file /Users/pengkunshuo/Desktop/root/blogggg/themes/next-reloaded/layout/_macro/post.swig.
    at Object.exports.throwError (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/utils.js:188:9)
    at parseTag (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:659:15)
    at /Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:778:15
    at Object.exports.each (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/utils.js:45:11)
    at Object.exports.parse (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:755:9)
    at exports.Swig.parse (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/swig.js:383:19)
    at exports.Swig.parseFile (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/swig.js:409:17)
    at TokenParser.<anonymous> (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/tags/import.js:61:21)
    at TokenParser.parseToken (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:174:15)
    at /Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:112:12
    at Object.exports.each (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/utils.js:45:11)
    at TokenParser.parse (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:102:11)
    at parseTag (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:708:12)
    at /Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:778:15
    at Object.exports.each (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/utils.js:45:11)
    at Object.exports.parse (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:755:9)
    at exports.Swig.parse (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/swig.js:383:19)
    at exports.Swig.precompile (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/swig.js:526:23)
    at Object.compile (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/swig.js:651:16)
    at Function.swigRenderer.compile (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/hexo/lib/plugins/renderer/swig.js:41:47)
    at Theme._View.View.View._precompile (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/hexo/lib/theme/view.js:116:31)
    at Theme._View.View.View (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/hexo/lib/theme/view.js:14:8)
    at new Theme._View.View (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/hexo/lib/theme/index.js:37:13)
    at Theme.setView (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/hexo/lib/theme/index.js:71:16)
    at file.read.then.result (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/hexo/lib/theme/processors/view.js:14:14)
    at tryCatcher (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/promise.js:569:18)
ERROR Process failed: layout/post.swig
Error: Unexpected end of tag "macro" on line 455 in file /Users/pengkunshuo/Desktop/root/blogggg/themes/next-reloaded/layout/_macro/post.swig.
    at Object.exports.throwError (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/utils.js:188:9)
    at parseTag (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:659:15)
    at /Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:778:15
    at Object.exports.each (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/utils.js:45:11)
    at Object.exports.parse (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:755:9)
    at exports.Swig.parse (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/swig.js:383:19)
    at exports.Swig.parseFile (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/swig.js:409:17)
    at TokenParser.<anonymous> (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/tags/import.js:61:21)
    at TokenParser.parseToken (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:174:15)
    at /Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:112:12
    at Object.exports.each (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/utils.js:45:11)
    at TokenParser.parse (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:102:11)
    at parseTag (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:708:12)
    at /Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:778:15
    at Object.exports.each (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/utils.js:45:11)
    at Object.exports.parse (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:755:9)
    at exports.Swig.parse (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/swig.js:383:19)
    at exports.Swig.precompile (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/swig.js:526:23)
    at Object.compile (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/swig.js:651:16)
    at Function.swigRenderer.compile (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/hexo/lib/plugins/renderer/swig.js:41:47)
    at Theme._View.View.View._precompile (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/hexo/lib/theme/view.js:116:31)
    at Theme._View.View.View (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/hexo/lib/theme/view.js:14:8)
    at new Theme._View.View (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/hexo/lib/theme/index.js:37:13)
    at Theme.setView (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/hexo/lib/theme/index.js:71:16)
    at file.read.then.result (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/hexo/lib/theme/processors/view.js:14:14)
    at tryCatcher (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/promise.js:569:18)
ERROR Theme config load failed.
ERROR Process failed: _config.yml
YAMLException: duplicated mapping key at line 738, column 1:
    baidu_site_verification: true
    ^
    at generateError (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
    at throwError (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
    at storeMappingPair (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/js-yaml/lib/js-yaml/loader.js:335:7)
    at readBlockMapping (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/js-yaml/lib/js-yaml/loader.js:1098:9)
    at composeNode (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
    at readDocument (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/js-yaml/lib/js-yaml/loader.js:1519:3)
    at loadDocuments (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/js-yaml/lib/js-yaml/loader.js:1575:5)
    at Object.load (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/js-yaml/lib/js-yaml/loader.js:1596:19)
    at Hexo.yamlHelper (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/hexo/lib/plugins/renderer/yaml.js:7:15)
    at Hexo.tryCatcher (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/method.js:15:34)
    at Promise.then.text (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/hexo/lib/hexo/render.js:60:20)
    at tryCatcher (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
ERROR Process failed: layout/_macro/post.swig
Error: Unexpected end of tag "macro" on line 455 in file /Users/pengkunshuo/Desktop/root/blogggg/themes/next-reloaded/layout/_macro/post.swig.
    at Object.exports.throwError (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/utils.js:188:9)
    at parseTag (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:659:15)
    at /Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:778:15
    at Object.exports.each (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/utils.js:45:11)
    at Object.exports.parse (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:755:9)
    at exports.Swig.parse (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/swig.js:383:19)
    at exports.Swig.precompile (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/swig.js:526:23)
    at Object.compile (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/swig.js:651:16)
    at Function.swigRenderer.compile (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/hexo/lib/plugins/renderer/swig.js:41:47)
    at Theme._View.View.View._precompile (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/hexo/lib/theme/view.js:116:31)
    at Theme._View.View.View (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/hexo/lib/theme/view.js:14:8)
    at new Theme._View.View (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/hexo/lib/theme/index.js:37:13)
    at Theme.setView (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/hexo/lib/theme/index.js:71:16)
    at file.read.then.result (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/hexo/lib/theme/processors/view.js:14:14)
    at tryCatcher (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/promise.js:638:18)
    at /Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/pengkunshuo/Desktop/root/blogggg/node_modules/graceful-fs/graceful-fs.js:90:16

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
v10.15.1

6.10.1

```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.9.0"
  },
  "dependencies": {
    "eslint": "^4.12.1",
    "gulp": "^4.0.0",
    "gulp-htmlclean": "^2.7.22",
    "gulp-htmlmin": "^5.0.1",
    "gulp-minify-css": "^1.2.4",
    "gulp-uglify": "^3.0.1",
    "hexo": "^3.9.0",
    "hexo-deployer-git": "^1.0.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-baidu-sitemap": "^0.1.6",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-index-pin-top": "^0.2.2",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-mathjax": "^0.6.0",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3",
    "hexo-tag-aplayer": "^3.0.4",
    "hexo-wordcount": "^6.0.1"
  }
}
```

#### Hexo version

```
hexo: 3.9.0
hexo-cli: 1.1.0
os: Darwin 18.6.0 darwin x64
http_parser: 2.8.0
node: 10.15.1
v8: 6.8.275.32-node.12
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
```
十分抱歉给各位带来困扰和不便！

**Comment by Flower233pks** [comment]
……实际上似乎问题集中在`Unexpected end of tag "macro" on line ... `上，但是并不知道该如何解决。

**Comment by stevenjoezhang** [comment]
检查`_config.yml`中的重复内容，例如`baidu_site_verification`
应该是merge conflict导致的

**Comment by stevenjoezhang** [comment]
检查`_config.yml`中的重复内容，例如`baidu_site_verification`

**Comment by Flower233pks** [comment]
> 检查`_config.yml`中的重复内容，例如`baidu_site_verification`

嗯，十分感谢，我也大致了解了问题所在，但是现在还有一个问题，就是似乎我盲目`git pull`使得新旧版本的部分设置杂糅了:
```cpp
ERROR Process failed: layout/index.swig
Error: Unexpected end of tag "macro" on line 455 in file /Users/pengkunshuo/Desktop/root/blogggg/themes/next-reloaded/layout/_macro/post.swig.
    at Object.exports.throwError (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/utils.js:188:9)
    at parseTag (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:659:15)
    at /Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:778:15
    at Object.exports.each (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/utils.js:45:11)
    at Object.exports.parse (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:755:9)
    at exports.Swig.parse (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/swig.js:383:19)
    at exports.Swig.parseFile (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/swig.js:409:17)
    at TokenParser.<anonymous> (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/tags/import.js:61:21)
    at TokenParser.parseToken (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:174:15)
    at /Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:112:12
    at Object.exports.each (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/utils.js:45:11)
    at TokenParser.parse (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:102:11)
    at parseTag (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:708:12)
    at /Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:778:15
    at Object.exports.each (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/utils.js:45:11)
    at Object.exports.parse (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:755:9)
    at exports.Swig.parse (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/swig.js:383:19)
    at exports.Swig.precompile (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/swig.js:526:23)
    at Object.compile (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/swig.js:651:16)
    at Function.swigRenderer.compile (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/hexo/lib/plugins/renderer/swig.js:41:47)
    at Theme._View.View.View._precompile (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/hexo/lib/theme/view.js:116:31)
    at Theme._View.View.View (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/hexo/lib/theme/view.js:14:8)
    at new Theme._View.View (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/hexo/lib/theme/index.js:37:13)
    at Theme.setView (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/hexo/lib/theme/index.js:71:16)
    at file.read.then.result (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/hexo/lib/theme/processors/view.js:14:14)
    at tryCatcher (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/promise.js:569:18)
ERROR Process failed: layout/post.swig
Error: Unexpected end of tag "macro" on line 455 in file /Users/pengkunshuo/Desktop/root/blogggg/themes/next-reloaded/layout/_macro/post.swig.
    at Object.exports.throwError (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/utils.js:188:9)
    at parseTag (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:659:15)
    at /Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:778:15
    at Object.exports.each (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/utils.js:45:11)
    at Object.exports.parse (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:755:9)
    at exports.Swig.parse (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/swig.js:383:19)
    at exports.Swig.parseFile (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/swig.js:409:17)
    at TokenParser.<anonymous> (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/tags/import.js:61:21)
    at TokenParser.parseToken (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:174:15)
    at /Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:112:12
    at Object.exports.each (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/utils.js:45:11)
    at TokenParser.parse (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:102:11)
    at parseTag (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:708:12)
    at /Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:778:15
    at Object.exports.each (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/utils.js:45:11)
    at Object.exports.parse (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:755:9)
    at exports.Swig.parse (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/swig.js:383:19)
    at exports.Swig.precompile (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/swig.js:526:23)
    at Object.compile (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/swig.js:651:16)
    at Function.swigRenderer.compile (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/hexo/lib/plugins/renderer/swig.js:41:47)
    at Theme._View.View.View._precompile (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/hexo/lib/theme/view.js:116:31)
    at Theme._View.View.View (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/hexo/lib/theme/view.js:14:8)
    at new Theme._View.View (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/hexo/lib/theme/index.js:37:13)
    at Theme.setView (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/hexo/lib/theme/index.js:71:16)
    at file.read.then.result (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/hexo/lib/theme/processors/view.js:14:14)
    at tryCatcher (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/promise.js:569:18)
ERROR Process failed: layout/_macro/post.swig
Error: Unexpected end of tag "macro" on line 455 in file /Users/pengkunshuo/Desktop/root/blogggg/themes/next-reloaded/layout/_macro/post.swig.
    at Object.exports.throwError (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/utils.js:188:9)
    at parseTag (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:659:15)
    at /Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:778:15
    at Object.exports.each (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/utils.js:45:11)
    at Object.exports.parse (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/parser.js:755:9)
    at exports.Swig.parse (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/swig.js:383:19)
    at exports.Swig.precompile (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/swig.js:526:23)
    at Object.compile (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/swig-templates/lib/swig.js:651:16)
    at Function.swigRenderer.compile (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/hexo/lib/plugins/renderer/swig.js:41:47)
    at Theme._View.View.View._precompile (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/hexo/lib/theme/view.js:116:31)
    at Theme._View.View.View (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/hexo/lib/theme/view.js:14:8)
    at new Theme._View.View (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/hexo/lib/theme/index.js:37:13)
    at Theme.setView (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/hexo/lib/theme/index.js:71:16)
    at file.read.then.result (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/hexo/lib/theme/processors/view.js:14:14)
    at tryCatcher (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/promise.js:638:18)
    at /Users/pengkunshuo/Desktop/root/blogggg/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/pengkunshuo/Desktop/root/blogggg/node_modules/graceful-fs/graceful-fs.js:90:16

```

这些问题在`hexo s`时依旧存在。但是在检查完上述文件之后发现并无什么明显瑕疵，所以我想知道是否是_config.yml里面哪个地方设置错误了？或者可否提供一个救治思路？

**Comment by stevenjoezhang** [comment]
检查一下是不是merge conflict造成的问题？

或者重新git clone最新版的主题，然后手动把以前更改过的内容设置好。

**Comment by Flower233pks** [comment]
嗯，十分感谢张学长，问题已经解决。

**Comment by jiangtj** [comment]
git操作上建议创新分支保存代替git stash
